[package]
name = "dolphin"
version = "0.1.0"
authors = ["eddie"]

[dependencies]
rand = "0.7.3"
lazy_static = "1.4.0"
typenum = "1.11.2"
num = "0.2.1"
enum_primitive = "0.1.1"
num-traits = "0.2"
num-derive = "0.3"
smallvec = "1.2.0"

[profile.release]
lto = true

