[package]
name = "dolphin"
version = "0.1.0"
authors = ["eddie"]

[dependencies]
rand = "0.7.3"
lazy_static = "1.4.0"
typenum = "1.11.2"
num = "0.2.1"
enum_primitive = "0.1.1"

[profile.release]
lto = true
codegen-units = 1
