[workspace]

members = [
    "dolphin_core",
    "dolphin_engine",
    "perft"
]


[profile.release]
lto = "fat"
codegen-units = 1
debug = false
opt-level = 3
overflow-checks=false
panic = "abort"
strip = "debuginfo"

[build]
rustflags = ["-C", "target-cpu=native"]
