[package]
name = "dolphin_core"
version = "0.1.0"
authors = ["eddiemcnally <emcn at gmx dot com>"]
edition = "2021"


[dependencies]
rand = "0.8.5"
rand_seeder = "0.2.3"
rand_xoshiro = "0.6.0"
core_affinity = "0.8.0"
num_enum = "0.5.11"
bitflags = "2.0.2"




